// Code generated by bpf2go; DO NOT EDIT.
//go:build 386 || amd64 || arm || arm64 || loong64 || mips64le || mipsle || ppc64le || riscv64 || wasm

package forwarder

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type XdpSmokeQosCpuPool struct {
	_        structs.HostLayout
	StartCpu uint32
	CpuCount uint32
}

type XdpSmokeQosDlFlowKey struct {
	_          structs.HostLayout
	UeIpv4     uint32
	RemoteIpv4 uint32
	UePort     uint16
	RemotePort uint16
	Proto      uint8
	Pad        [3]uint8
}

type XdpSmokeQosFlowInfo struct {
	_        structs.HostLayout
	Qfi      uint8
	Pad      [3]uint8
	QosClass uint32
}

type XdpSmokeQosUlFlowKey struct {
	_    structs.HostLayout
	Teid uint32
	Qfi  uint8
	Pad  [3]uint8
}

// LoadXdpSmoke returns the embedded CollectionSpec for XdpSmoke.
func LoadXdpSmoke() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_XdpSmokeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load XdpSmoke: %w", err)
	}

	return spec, err
}

// LoadXdpSmokeObjects loads XdpSmoke and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*XdpSmokeObjects
//	*XdpSmokePrograms
//	*XdpSmokeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadXdpSmokeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadXdpSmoke()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// XdpSmokeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSmokeSpecs struct {
	XdpSmokeProgramSpecs
	XdpSmokeMapSpecs
	XdpSmokeVariableSpecs
}

// XdpSmokeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSmokeProgramSpecs struct {
	UpfXdpQos *ebpf.ProgramSpec `ebpf:"upf_xdp_qos"`
}

// XdpSmokeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSmokeMapSpecs struct {
	DlDefaultQosMap *ebpf.MapSpec `ebpf:"dl_default_qos_map"`
	DlExactQosMap   *ebpf.MapSpec `ebpf:"dl_exact_qos_map"`
	QosCpuMap       *ebpf.MapSpec `ebpf:"qos_cpu_map"`
	QosCpuPoolMap   *ebpf.MapSpec `ebpf:"qos_cpu_pool_map"`
	UlFlowQosMap    *ebpf.MapSpec `ebpf:"ul_flow_qos_map"`
	XdpStatsMap     *ebpf.MapSpec `ebpf:"xdp_stats_map"`
}

// XdpSmokeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type XdpSmokeVariableSpecs struct {
}

// XdpSmokeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSmokeObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSmokeObjects struct {
	XdpSmokePrograms
	XdpSmokeMaps
	XdpSmokeVariables
}

func (o *XdpSmokeObjects) Close() error {
	return _XdpSmokeClose(
		&o.XdpSmokePrograms,
		&o.XdpSmokeMaps,
	)
}

// XdpSmokeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSmokeObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSmokeMaps struct {
	DlDefaultQosMap *ebpf.Map `ebpf:"dl_default_qos_map"`
	DlExactQosMap   *ebpf.Map `ebpf:"dl_exact_qos_map"`
	QosCpuMap       *ebpf.Map `ebpf:"qos_cpu_map"`
	QosCpuPoolMap   *ebpf.Map `ebpf:"qos_cpu_pool_map"`
	UlFlowQosMap    *ebpf.Map `ebpf:"ul_flow_qos_map"`
	XdpStatsMap     *ebpf.Map `ebpf:"xdp_stats_map"`
}

func (m *XdpSmokeMaps) Close() error {
	return _XdpSmokeClose(
		m.DlDefaultQosMap,
		m.DlExactQosMap,
		m.QosCpuMap,
		m.QosCpuPoolMap,
		m.UlFlowQosMap,
		m.XdpStatsMap,
	)
}

// XdpSmokeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSmokeObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSmokeVariables struct {
}

// XdpSmokePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadXdpSmokeObjects or ebpf.CollectionSpec.LoadAndAssign.
type XdpSmokePrograms struct {
	UpfXdpQos *ebpf.Program `ebpf:"upf_xdp_qos"`
}

func (p *XdpSmokePrograms) Close() error {
	return _XdpSmokeClose(
		p.UpfXdpQos,
	)
}

func _XdpSmokeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed xdpsmoke_bpfel.o
var _XdpSmokeBytes []byte
